### ISSUE TITLE
gitspatial.com is offline

### ISSUE THREAD

**Issue by timlinux** [JasonSanford/gitspatial#15]
Hi

I am interested to try out your cool looking project, however http://gitspatial seems to be offline and it seems to be an integral component to using your work. Could you direct me to the source of gitspatial (if available) so that we could self-host, or otherwise give an indication on the planned availability of gitspatial?

Thanks

Tim

**Comment by JasonSanford** [comment]
Hi Tim, I took GitSpatial offline quite a few months ago, as no one was using it. It was a fun project, but just didn't see anyone really using it so I wanted to stop paying for hosting.

The source of GitSpatial is this repo. The readme isn't the best, but the [development](https://github.com/JasonSanford/gitspatial#development) section should hopefully have enough information to get you up and running. If you run into any problems let me know and I'll try to help.

**Comment by timlinux** [comment]
@JasonSanford ah thanks so much - I'm sure I will figure it out - would love to spin it up and kick the tires! Since I am a docker junkie I will probably 'dockerify' it in the process - are you interested in patches if I do that?

**Comment by JasonSanford** [comment]
Definitely!
