### ISSUE TITLE
Catch GEOS Errors

### ISSUE THREAD

**Issue by JasonSanford** [JasonSanford/gitspatial#4]
INFO 2013-09-26 14:05:54,583 gitspatial.tasks Setting feature set sync status as syncing: mikelmaron/kenya-election-data/data/counties.geojson
INFO 2013-09-26 14:05:54,601 requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): api.github.com
INFO 2013-09-26 14:05:54,707 requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): api.github.com
INFO 2013-09-26 14:05:54,761 requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): api.github.com
INFO 2013-09-26 14:05:55,567 requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): api.github.com
INFO 2013-09-26 14:05:56,897 gitspatial.tasks Created Feature: <Feature 189154 from mikelmaron/kenya-election-data/data/counties.geojson>
INFO 2013-09-26 14:05:56,901 gitspatial.tasks Created Feature: <Feature 189155 from mikelmaron/kenya-election-data/data/counties.geojson>
INFO 2013-09-26 14:05:56,905 gitspatial.tasks Created Feature: <Feature 189156 from mikelmaron/kenya-election-data/data/counties.geojson>
INFO 2013-09-26 14:05:56,914 gitspatial.tasks Created Feature: <Feature 189157 from mikelmaron/kenya-election-data/data/counties.geojson>
INFO 2013-09-26 14:05:56,924 gitspatial.tasks Created Feature: <Feature 189158 from mikelmaron/kenya-election-data/data/counties.geojson>
INFO 2013-09-26 14:05:56,927 gitspatial.tasks Created Feature: <Feature 189159 from mikelmaron/kenya-election-data/data/counties.geojson>
INFO 2013-09-26 14:05:56,933 gitspatial.tasks Created Feature: <Feature 189160 from mikelmaron/kenya-election-data/data/counties.geojson>
INFO 2013-09-26 14:05:56,945 gitspatial.tasks Created Feature: <Feature 189161 from mikelmaron/kenya-election-data/data/counties.geojson>
INFO 2013-09-26 14:05:56,957 gitspatial.tasks Created Feature: <Feature 189162 from mikelmaron/kenya-election-data/data/counties.geojson>
ERROR 2013-09-26 14:05:56,957 django.contrib.gis GEOS_ERROR: IllegalArgumentException: Points of LinearRing do not form a closed linestring

ERROR 2013-09-26 14:05:56,957 django.contrib.gis GEOS_ERROR: IllegalArgumentException: Points of LinearRing do not form a closed linestring

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/gitspatial/apps/gitspatial/venv/local/lib/python2.7/site-packages/celery/app/task.py", line 330, in **call**
    return self.run(_args, *_kwargs)
  File "/home/gitspatial/apps/gitspatial/gitspatial/tasks.py", line 139, in get_feature_set_features
    geom = GEOSGeometry(json.dumps(zs_stripped))
  File "/home/gitspatial/apps/gitspatial/venv/local/lib/python2.7/site-packages/django/contrib/gis/geos/geometry.py", line 75, in **init**
    g = wkb_r().read(gdal.OGRGeometry(geo_input).wkb)
  File "/home/gitspatial/apps/gitspatial/venv/local/lib/python2.7/site-packages/django/contrib/gis/geos/prototypes/io.py", line 138, in read
    return wkb_reader_read(self.ptr, wkb_s, len(wkb_s))
  File "/home/gitspatial/apps/gitspatial/venv/local/lib/python2.7/site-packages/django/contrib/gis/geos/prototypes/threadsafe.py", line 49, in **call**
    return self.cfunc(self.thread_context.handle.ptr, *args)
  File "/home/gitspatial/apps/gitspatial/venv/local/lib/python2.7/site-packages/django/contrib/gis/geos/prototypes/errcheck.py", line 43, in check_geom
    raise GEOSException('Error encountered checking Geometry returned from GEOS C function "%s".' % func.**name**)
GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKBReader_read_r".

**Comment by speg** [comment]
@JasonSanford what was the fix for this? Was it just bad data?
